/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicLayoutRouteRouteImport } from './routes/_publicLayout/route'
import { Route as HomeLayoutRouteRouteImport } from './routes/_homeLayout/route'
import { Route as HomeLayoutIndexRouteImport } from './routes/_homeLayout/index'
import { Route as HomeLayoutSettingsIndexRouteImport } from './routes/_homeLayout/settings/index'
import { Route as HomeLayoutProfileIndexRouteImport } from './routes/_homeLayout/profile/index'
import { Route as HomeLayoutExpenseIndexRouteImport } from './routes/_homeLayout/expense/index'
import { Route as PublicLayoutAuthRegisterIndexRouteImport } from './routes/_publicLayout/auth/register/index'
import { Route as PublicLayoutAuthLoginIndexRouteImport } from './routes/_publicLayout/auth/login/index'
import { Route as HomeLayoutSettingsNotificationsIndexRouteImport } from './routes/_homeLayout/settings/notifications/index'
import { Route as HomeLayoutSettingsBudgetGoalsIndexRouteImport } from './routes/_homeLayout/settings/budget-goals/index'

const PublicLayoutRouteRoute = PublicLayoutRouteRouteImport.update({
  id: '/_publicLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeLayoutRouteRoute = HomeLayoutRouteRouteImport.update({
  id: '/_homeLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeLayoutIndexRoute = HomeLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HomeLayoutRouteRoute,
} as any)
const HomeLayoutSettingsIndexRoute = HomeLayoutSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => HomeLayoutRouteRoute,
} as any)
const HomeLayoutProfileIndexRoute = HomeLayoutProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => HomeLayoutRouteRoute,
} as any)
const HomeLayoutExpenseIndexRoute = HomeLayoutExpenseIndexRouteImport.update({
  id: '/expense/',
  path: '/expense/',
  getParentRoute: () => HomeLayoutRouteRoute,
} as any)
const PublicLayoutAuthRegisterIndexRoute =
  PublicLayoutAuthRegisterIndexRouteImport.update({
    id: '/auth/register/',
    path: '/auth/register/',
    getParentRoute: () => PublicLayoutRouteRoute,
  } as any)
const PublicLayoutAuthLoginIndexRoute =
  PublicLayoutAuthLoginIndexRouteImport.update({
    id: '/auth/login/',
    path: '/auth/login/',
    getParentRoute: () => PublicLayoutRouteRoute,
  } as any)
const HomeLayoutSettingsNotificationsIndexRoute =
  HomeLayoutSettingsNotificationsIndexRouteImport.update({
    id: '/settings/notifications/',
    path: '/settings/notifications/',
    getParentRoute: () => HomeLayoutRouteRoute,
  } as any)
const HomeLayoutSettingsBudgetGoalsIndexRoute =
  HomeLayoutSettingsBudgetGoalsIndexRouteImport.update({
    id: '/settings/budget-goals/',
    path: '/settings/budget-goals/',
    getParentRoute: () => HomeLayoutRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof HomeLayoutIndexRoute
  '/expense/': typeof HomeLayoutExpenseIndexRoute
  '/profile/': typeof HomeLayoutProfileIndexRoute
  '/settings/': typeof HomeLayoutSettingsIndexRoute
  '/settings/budget-goals/': typeof HomeLayoutSettingsBudgetGoalsIndexRoute
  '/settings/notifications/': typeof HomeLayoutSettingsNotificationsIndexRoute
  '/auth/login/': typeof PublicLayoutAuthLoginIndexRoute
  '/auth/register/': typeof PublicLayoutAuthRegisterIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof HomeLayoutIndexRoute
  '/expense': typeof HomeLayoutExpenseIndexRoute
  '/profile': typeof HomeLayoutProfileIndexRoute
  '/settings': typeof HomeLayoutSettingsIndexRoute
  '/settings/budget-goals': typeof HomeLayoutSettingsBudgetGoalsIndexRoute
  '/settings/notifications': typeof HomeLayoutSettingsNotificationsIndexRoute
  '/auth/login': typeof PublicLayoutAuthLoginIndexRoute
  '/auth/register': typeof PublicLayoutAuthRegisterIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_homeLayout': typeof HomeLayoutRouteRouteWithChildren
  '/_publicLayout': typeof PublicLayoutRouteRouteWithChildren
  '/_homeLayout/': typeof HomeLayoutIndexRoute
  '/_homeLayout/expense/': typeof HomeLayoutExpenseIndexRoute
  '/_homeLayout/profile/': typeof HomeLayoutProfileIndexRoute
  '/_homeLayout/settings/': typeof HomeLayoutSettingsIndexRoute
  '/_homeLayout/settings/budget-goals/': typeof HomeLayoutSettingsBudgetGoalsIndexRoute
  '/_homeLayout/settings/notifications/': typeof HomeLayoutSettingsNotificationsIndexRoute
  '/_publicLayout/auth/login/': typeof PublicLayoutAuthLoginIndexRoute
  '/_publicLayout/auth/register/': typeof PublicLayoutAuthRegisterIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/expense/'
    | '/profile/'
    | '/settings/'
    | '/settings/budget-goals/'
    | '/settings/notifications/'
    | '/auth/login/'
    | '/auth/register/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/expense'
    | '/profile'
    | '/settings'
    | '/settings/budget-goals'
    | '/settings/notifications'
    | '/auth/login'
    | '/auth/register'
  id:
    | '__root__'
    | '/_homeLayout'
    | '/_publicLayout'
    | '/_homeLayout/'
    | '/_homeLayout/expense/'
    | '/_homeLayout/profile/'
    | '/_homeLayout/settings/'
    | '/_homeLayout/settings/budget-goals/'
    | '/_homeLayout/settings/notifications/'
    | '/_publicLayout/auth/login/'
    | '/_publicLayout/auth/register/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  HomeLayoutRouteRoute: typeof HomeLayoutRouteRouteWithChildren
  PublicLayoutRouteRoute: typeof PublicLayoutRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_publicLayout': {
      id: '/_publicLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_homeLayout': {
      id: '/_homeLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof HomeLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_homeLayout/': {
      id: '/_homeLayout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof HomeLayoutIndexRouteImport
      parentRoute: typeof HomeLayoutRouteRoute
    }
    '/_homeLayout/settings/': {
      id: '/_homeLayout/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof HomeLayoutSettingsIndexRouteImport
      parentRoute: typeof HomeLayoutRouteRoute
    }
    '/_homeLayout/profile/': {
      id: '/_homeLayout/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof HomeLayoutProfileIndexRouteImport
      parentRoute: typeof HomeLayoutRouteRoute
    }
    '/_homeLayout/expense/': {
      id: '/_homeLayout/expense/'
      path: '/expense'
      fullPath: '/expense/'
      preLoaderRoute: typeof HomeLayoutExpenseIndexRouteImport
      parentRoute: typeof HomeLayoutRouteRoute
    }
    '/_publicLayout/auth/register/': {
      id: '/_publicLayout/auth/register/'
      path: '/auth/register'
      fullPath: '/auth/register/'
      preLoaderRoute: typeof PublicLayoutAuthRegisterIndexRouteImport
      parentRoute: typeof PublicLayoutRouteRoute
    }
    '/_publicLayout/auth/login/': {
      id: '/_publicLayout/auth/login/'
      path: '/auth/login'
      fullPath: '/auth/login/'
      preLoaderRoute: typeof PublicLayoutAuthLoginIndexRouteImport
      parentRoute: typeof PublicLayoutRouteRoute
    }
    '/_homeLayout/settings/notifications/': {
      id: '/_homeLayout/settings/notifications/'
      path: '/settings/notifications'
      fullPath: '/settings/notifications/'
      preLoaderRoute: typeof HomeLayoutSettingsNotificationsIndexRouteImport
      parentRoute: typeof HomeLayoutRouteRoute
    }
    '/_homeLayout/settings/budget-goals/': {
      id: '/_homeLayout/settings/budget-goals/'
      path: '/settings/budget-goals'
      fullPath: '/settings/budget-goals/'
      preLoaderRoute: typeof HomeLayoutSettingsBudgetGoalsIndexRouteImport
      parentRoute: typeof HomeLayoutRouteRoute
    }
  }
}

interface HomeLayoutRouteRouteChildren {
  HomeLayoutIndexRoute: typeof HomeLayoutIndexRoute
  HomeLayoutExpenseIndexRoute: typeof HomeLayoutExpenseIndexRoute
  HomeLayoutProfileIndexRoute: typeof HomeLayoutProfileIndexRoute
  HomeLayoutSettingsIndexRoute: typeof HomeLayoutSettingsIndexRoute
  HomeLayoutSettingsBudgetGoalsIndexRoute: typeof HomeLayoutSettingsBudgetGoalsIndexRoute
  HomeLayoutSettingsNotificationsIndexRoute: typeof HomeLayoutSettingsNotificationsIndexRoute
}

const HomeLayoutRouteRouteChildren: HomeLayoutRouteRouteChildren = {
  HomeLayoutIndexRoute: HomeLayoutIndexRoute,
  HomeLayoutExpenseIndexRoute: HomeLayoutExpenseIndexRoute,
  HomeLayoutProfileIndexRoute: HomeLayoutProfileIndexRoute,
  HomeLayoutSettingsIndexRoute: HomeLayoutSettingsIndexRoute,
  HomeLayoutSettingsBudgetGoalsIndexRoute:
    HomeLayoutSettingsBudgetGoalsIndexRoute,
  HomeLayoutSettingsNotificationsIndexRoute:
    HomeLayoutSettingsNotificationsIndexRoute,
}

const HomeLayoutRouteRouteWithChildren = HomeLayoutRouteRoute._addFileChildren(
  HomeLayoutRouteRouteChildren,
)

interface PublicLayoutRouteRouteChildren {
  PublicLayoutAuthLoginIndexRoute: typeof PublicLayoutAuthLoginIndexRoute
  PublicLayoutAuthRegisterIndexRoute: typeof PublicLayoutAuthRegisterIndexRoute
}

const PublicLayoutRouteRouteChildren: PublicLayoutRouteRouteChildren = {
  PublicLayoutAuthLoginIndexRoute: PublicLayoutAuthLoginIndexRoute,
  PublicLayoutAuthRegisterIndexRoute: PublicLayoutAuthRegisterIndexRoute,
}

const PublicLayoutRouteRouteWithChildren =
  PublicLayoutRouteRoute._addFileChildren(PublicLayoutRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  HomeLayoutRouteRoute: HomeLayoutRouteRouteWithChildren,
  PublicLayoutRouteRoute: PublicLayoutRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
