/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TransactionIndexRouteImport } from './routes/transaction/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as RegisterIndexRouteImport } from './routes/register/index'
import { Route as SettingsNotificationsIndexRouteImport } from './routes/settings/notifications/index'
import { Route as SettingsBudgetGoalsIndexRouteImport } from './routes/settings/budget-goals/index'
import { Route as AuthProfileIndexRouteImport } from './routes/auth/profile/index'
import { Route as AuthLoginIndexRouteImport } from './routes/auth/login/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionIndexRoute = TransactionIndexRouteImport.update({
  id: '/transaction/',
  path: '/transaction/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterIndexRoute = RegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsNotificationsIndexRoute =
  SettingsNotificationsIndexRouteImport.update({
    id: '/settings/notifications/',
    path: '/settings/notifications/',
    getParentRoute: () => rootRouteImport,
  } as any)
const SettingsBudgetGoalsIndexRoute =
  SettingsBudgetGoalsIndexRouteImport.update({
    id: '/settings/budget-goals/',
    path: '/settings/budget-goals/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthProfileIndexRoute = AuthProfileIndexRouteImport.update({
  id: '/auth/profile/',
  path: '/auth/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/auth/login/',
  path: '/auth/login/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/register/': typeof RegisterIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/transaction/': typeof TransactionIndexRoute
  '/auth/login/': typeof AuthLoginIndexRoute
  '/auth/profile/': typeof AuthProfileIndexRoute
  '/settings/budget-goals/': typeof SettingsBudgetGoalsIndexRoute
  '/settings/notifications/': typeof SettingsNotificationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/register': typeof RegisterIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/transaction': typeof TransactionIndexRoute
  '/auth/login': typeof AuthLoginIndexRoute
  '/auth/profile': typeof AuthProfileIndexRoute
  '/settings/budget-goals': typeof SettingsBudgetGoalsIndexRoute
  '/settings/notifications': typeof SettingsNotificationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/register/': typeof RegisterIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/transaction/': typeof TransactionIndexRoute
  '/auth/login/': typeof AuthLoginIndexRoute
  '/auth/profile/': typeof AuthProfileIndexRoute
  '/settings/budget-goals/': typeof SettingsBudgetGoalsIndexRoute
  '/settings/notifications/': typeof SettingsNotificationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/register/'
    | '/settings/'
    | '/transaction/'
    | '/auth/login/'
    | '/auth/profile/'
    | '/settings/budget-goals/'
    | '/settings/notifications/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/register'
    | '/settings'
    | '/transaction'
    | '/auth/login'
    | '/auth/profile'
    | '/settings/budget-goals'
    | '/settings/notifications'
  id:
    | '__root__'
    | '/'
    | '/register/'
    | '/settings/'
    | '/transaction/'
    | '/auth/login/'
    | '/auth/profile/'
    | '/settings/budget-goals/'
    | '/settings/notifications/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RegisterIndexRoute: typeof RegisterIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  TransactionIndexRoute: typeof TransactionIndexRoute
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  AuthProfileIndexRoute: typeof AuthProfileIndexRoute
  SettingsBudgetGoalsIndexRoute: typeof SettingsBudgetGoalsIndexRoute
  SettingsNotificationsIndexRoute: typeof SettingsNotificationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transaction/': {
      id: '/transaction/'
      path: '/transaction'
      fullPath: '/transaction/'
      preLoaderRoute: typeof TransactionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/': {
      id: '/register/'
      path: '/register'
      fullPath: '/register/'
      preLoaderRoute: typeof RegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/notifications/': {
      id: '/settings/notifications/'
      path: '/settings/notifications'
      fullPath: '/settings/notifications/'
      preLoaderRoute: typeof SettingsNotificationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/budget-goals/': {
      id: '/settings/budget-goals/'
      path: '/settings/budget-goals'
      fullPath: '/settings/budget-goals/'
      preLoaderRoute: typeof SettingsBudgetGoalsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/profile/': {
      id: '/auth/profile/'
      path: '/auth/profile'
      fullPath: '/auth/profile/'
      preLoaderRoute: typeof AuthProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login/': {
      id: '/auth/login/'
      path: '/auth/login'
      fullPath: '/auth/login/'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RegisterIndexRoute: RegisterIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  TransactionIndexRoute: TransactionIndexRoute,
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  AuthProfileIndexRoute: AuthProfileIndexRoute,
  SettingsBudgetGoalsIndexRoute: SettingsBudgetGoalsIndexRoute,
  SettingsNotificationsIndexRoute: SettingsNotificationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
