/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TransactionIndexRouteImport } from './routes/transaction/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as SettingsNotificationsIndexRouteImport } from './routes/settings/notifications/index'
import { Route as SettingsBudgetGoalsIndexRouteImport } from './routes/settings/budget-goals/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionIndexRoute = TransactionIndexRouteImport.update({
  id: '/transaction/',
  path: '/transaction/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsNotificationsIndexRoute =
  SettingsNotificationsIndexRouteImport.update({
    id: '/settings/notifications/',
    path: '/settings/notifications/',
    getParentRoute: () => rootRouteImport,
  } as any)
const SettingsBudgetGoalsIndexRoute =
  SettingsBudgetGoalsIndexRouteImport.update({
    id: '/settings/budget-goals/',
    path: '/settings/budget-goals/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/transaction/': typeof TransactionIndexRoute
  '/settings/budget-goals/': typeof SettingsBudgetGoalsIndexRoute
  '/settings/notifications/': typeof SettingsNotificationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/profile': typeof ProfileIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/transaction': typeof TransactionIndexRoute
  '/settings/budget-goals': typeof SettingsBudgetGoalsIndexRoute
  '/settings/notifications': typeof SettingsNotificationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/transaction/': typeof TransactionIndexRoute
  '/settings/budget-goals/': typeof SettingsBudgetGoalsIndexRoute
  '/settings/notifications/': typeof SettingsNotificationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/profile/'
    | '/settings/'
    | '/transaction/'
    | '/settings/budget-goals/'
    | '/settings/notifications/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/profile'
    | '/settings'
    | '/transaction'
    | '/settings/budget-goals'
    | '/settings/notifications'
  id:
    | '__root__'
    | '/'
    | '/profile/'
    | '/settings/'
    | '/transaction/'
    | '/settings/budget-goals/'
    | '/settings/notifications/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  TransactionIndexRoute: typeof TransactionIndexRoute
  SettingsBudgetGoalsIndexRoute: typeof SettingsBudgetGoalsIndexRoute
  SettingsNotificationsIndexRoute: typeof SettingsNotificationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transaction/': {
      id: '/transaction/'
      path: '/transaction'
      fullPath: '/transaction/'
      preLoaderRoute: typeof TransactionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/notifications/': {
      id: '/settings/notifications/'
      path: '/settings/notifications'
      fullPath: '/settings/notifications/'
      preLoaderRoute: typeof SettingsNotificationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/budget-goals/': {
      id: '/settings/budget-goals/'
      path: '/settings/budget-goals'
      fullPath: '/settings/budget-goals/'
      preLoaderRoute: typeof SettingsBudgetGoalsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  TransactionIndexRoute: TransactionIndexRoute,
  SettingsBudgetGoalsIndexRoute: SettingsBudgetGoalsIndexRoute,
  SettingsNotificationsIndexRoute: SettingsNotificationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
